### ISSUE TITLE
Detect .scalafmt.conf

### ISSUE THREAD

**Issue by gabro** [gabro/vscode-scalafmt#1]
Currently the extension uses the default configuration.
As soon as the JS facade accepts options, we should look for a `.scalafmt.conf` file in the current workspace and use those options.

**Comment by gabro** [comment]
Currently blocked by https://github.com/olafurpg/metaconfig/issues/28

**Comment by jvican** [comment]
So looking forward to this!

**Comment by gabro** [comment]
I talked to @olafurpg and I think I'll fallback to manual construction of a ScalafmtConfig object, since metaconfig is unreliable for JS and it's going to be phased out anyway. I'll keep you posted ;)

**Comment by gabro** [comment]
Almost there!

![](http://g.recordit.co/dpevADf0aN.gif)

**Comment by jvican** [comment]
Thanks! Will try it out today :tada:.

**Comment by jvican** [comment]
I'm using this successfully. 👍
