### ISSUE TITLE
"Format Document" does not format the sources

### ISSUE THREAD

**Issue by jvican** [gabro/vscode-scalafmt#3]
I'm using https://github.com/dragos/dragos-vscode-scala/commits/bc38084b8fbcd5f498e1217375281cccbc4ff798, and when I install this dependency, "Format Document" does nothing.
  
Is there any way we can debug what the entension does?

**Comment by gabro** [comment]
That's odd. To debug this the easiest way is to open this extension as a project in vscode, go to the debug panel, click on "run extension".
Then you can use the extension on the second window it opens, and see the debug console in the first window (you can put breakpoints)

**Comment by jvican** [comment]
Nevermind, it must have been something else because now it;s working 👿 Thanks! I'm on my way to switching off Intellij.

**Comment by gabro** [comment]
🙌
