### ISSUE TITLE
Formatting fails on *.sbt files

### ISSUE THREAD

**Issue by jto** [gabro/vscode-scalafmt#7]
This issue https://github.com/scalameta/scalafmt/issues/405 seems to suggest that scalafmt support formatting *.sbt files but to fails when using this plugin.

**Comment by gabro** [comment]
Hey @jto, thanks for reporting. The detection of `.sbt` files was "naive" and it depended on the specific plugin you installed for syntax.

I've fixed this in 23d56feae310b5862f665f27a1be9877ef9c3286 and released the fix as 0.1.2.

Try it out and let me know if it works now!

**Comment by jto** [comment]
Can confirm it works 👍
