### ISSUE TITLE
"java.lang.Error: End:5:1 ..."// Vertica"" on fresh install.

### ISSUE THREAD

**Issue by Daenyth** [gabro/vscode-scalafmt#8]
Mostly fresh install of vscode, running on this file: https://github.com/Daenyth/http4s/blob/d95f22ebd49735d3dac8bd0c64e3e0f461b7a89c/aws-signer/src/main/scala/http4s/aws/middleware/AwsSigner.scala

```
An error occurred while formatting this file with Scalafmt:

java.lang.Error: End:5:1 ..."// Vertica"
If this is unexpected, consider filing an issue at https://github.com/gabro/vscode-scalafmt/issues/new
```

**Comment by gabro** [comment]
That's due to a bug in the scalajs version hocon parser, try removing the comment in the scalafmt.conf and see whether it fixes is

**Comment by gabro** [comment]
Slightly better workaround: try using # instead of // for the comment

**Comment by gabro** [comment]
Closing as this extension is now deprecated in favor of Metals
